export const API_ROUTES = {
  health: '/health',
  runs: '/runs',
  runDetail: '/runs/{run_id}',
  artifacts: '/runs/{run_id}/artifacts',
  verification: '/runs/{run_id}/verification',
  overview: '/runs/{run_id}/overview',
  network: '/runs/{run_id}/network',
  centrality: '/runs/{run_id}/centrality',
  centralityLeaders: '/runs/{run_id}/centrality-leaders',
  communities: '/runs/{run_id}/communities',
  communityDetail: '/runs/{run_id}/communities/{community_id}',
  topics: '/runs/{run_id}/topics',
  communityTopics: '/runs/{run_id}/topics/{community_id}',
  themes: '/runs/{run_id}/themes',
  communityThemes: '/runs/{run_id}/themes/{community_id}',
  monthlyThemeTrends: '/runs/{run_id}/theme-trends/monthly',
  themeTimeline: '/runs/{run_id}/theme-trends/timeline',
  monthlyThemeClusters: '/runs/{run_id}/theme-clusters/monthly',
  clusteredThemeTimeline: '/runs/{run_id}/theme-clusters/timeline',
  clusteredThemeEvidence: '/runs/{run_id}/theme-clusters/evidence',
  transitions: '/runs/{run_id}/transitions',
  persistentCommunities: '/runs/{run_id}/persistent-communities',
  membershipChanges: '/runs/{run_id}/membership-changes',
  themeSimilarity: '/runs/{run_id}/theme-similarity',
  evolutionPaths: '/runs/{run_id}/evolution/paths',
  evolutionPathMobility: '/runs/{run_id}/evolution/paths/{path_id}/mobility',
  evolutionPathThemeSimilarity: '/runs/{run_id}/evolution/paths/{path_id}/theme-similarity',
  report: '/runs/{run_id}/report',
  download: '/runs/{run_id}/downloads/{artifact_key}',
} as const;

export const API_QUERY_KEYS = {
  runs: ['platform', 'content_type', 'year', 'month', 'status'],
  verification: ['deep'],
  network: ['metric', 'period', 'view', 'sampling', 'community_id', 'max_nodes', 'max_edges', 'min_weight'],
  centrality: ['limit', 'offset'],
  centralityLeaders: ['metric', 'period'],
  communities: ['metric', 'period', 'limit', 'offset'],
  communityDetail: ['metric', 'period', 'max_nodes', 'max_edges', 'min_weight'],
  topics: ['type', 'community_id', 'period', 'limit', 'offset'],
  communityTopics: ['type', 'period', 'limit', 'offset'],
  themes: ['month', 'period', 'community_id', 'exact_theme', 'limit', 'offset'],
  communityThemes: ['month', 'period', 'exact_theme', 'limit', 'offset'],
  monthlyThemeTrends: ['period', 'scope'],
  themeTimeline: ['period_start', 'period_end', 'scope'],
  monthlyThemeClusters: ['period', 'scope'],
  clusteredThemeTimeline: ['period_start', 'period_end', 'scope'],
  clusteredThemeEvidence: ['period', 'canonical_theme_id', 'limit', 'offset'],
  transitions: ['limit', 'offset'],
  evolutionPathThemeSimilarity: ['theme_type'],
} as const;

export function fillRoute(
  template: string,
  values: Record<string, string>,
): string {
  return Object.entries(values).reduce(
    (path, [key, value]) => path.replace(`{${key}}`, encodeURIComponent(value)),
    template,
  );
}
