data_type: twitter
content_type: retweet_quote
month: "02"
year: "2017"

input_path: <LOCAL_PROJECT_PATH>/Projects/Telegram/cleaned_code/data/twitter-neo4j/monthly_retweet/retweet_february_2017.csv
output_base_path: outputs/my-retweet-2017/

creator_relation: TWEETED
spreader_relation: RETWEETED_BY

creator_node_column: source
spreader_node_column: target
text_node_column: target
date_column: created_at

graph_thresholds:
  min_total_post: 10
  min_shared_post: 5
  min_members: 3

lda:
  num_topics: 15
  top_n_keywords: 50

theme:
  enable_gpt: false
  model: gpt-4o
  sleep_seconds: 2
  transition_threshold: 0.5
  output_dir: outputs/my-retweet-2017-theme/
  year: "2017"
  render_visuals: false
  similarity_model: paraphrase-MiniLM-L6-v2