data_type: telegram
content_type: forward
month: "october"
year: "2019"
input_path: data/telegram-neo4j-sample/samples_500_per_month/sample_translated_october_2019.csv
output_base_path: results/
creator_relation: PRODUCED
spreader_relation: FORWARDED_BY
creator_node_column: target
spreader_node_column: source
text_node_column: text_translated
date_column: date

database:
  engine: memgraph
  uri: ${GRAPH_DB_URI}
  user: ${GRAPH_DB_USER}
  password: ${GRAPH_DB_PASSWORD}

graph_thresholds:
  min_total_post: 1
  min_shared_post: 1
  min_members: 2

lda:
  num_topics: 15
  top_n_keywords: 50
